/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "log_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
log_action_1(log_action_args arg1, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, LOG_ACTION,
		(xdrproc_t) xdr_log_action_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
