/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log_rpc.h"

bool_t
xdr_log_action_args (XDR *xdrs, log_action_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 512))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, 32))
		 return FALSE;
	return TRUE;
}
