/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_RPC_H_RPCGEN
#define _LOG_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct log_action_args {
	char *user;
	char *operation;
	char *timestamp;
};
typedef struct log_action_args log_action_args;

#define LOGPROG 0x20000001
#define LOGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_ACTION 1
extern  enum clnt_stat log_action_1(log_action_args , void *, CLIENT *);
extern  bool_t log_action_1_svc(log_action_args , void *, struct svc_req *);
extern int logprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_ACTION 1
extern  enum clnt_stat log_action_1();
extern  bool_t log_action_1_svc();
extern int logprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_action_args (XDR *, log_action_args*);

#else /* K&R C */
extern bool_t xdr_log_action_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_RPC_H_RPCGEN */
