/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "log_rpc.h"

bool_t
log_action_1_svc(log_action_args arg1, void *result,  struct svc_req *rqstp)
{
	/* Imprime: Nombre_usuario OPERACION [<fichero>]  dd/mm/yyyy hh:mm:ss */
    printf("%s %s %s\n",
		arg1.user,
		arg1.operation,
		arg1.timestamp);
	fflush(stdout);
	return 1;

}

int
logprog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
